server:
  port: 9999
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://112.74.42.138:8848
  cloud:
    # 表示要订阅服务的服务名，可以配置'*'，
    # 代表订阅所有服务，不推荐使用。若需订阅多应用，使用 "," 分割
    subscribed-services: dubbo-provider


spring:
  application:
    name: dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 112.74.42.138:8848
  main:
    allow-bean-definition-overriding: true